MvcApplication2/Controllers/EmpController.cs
using MvcApplication2.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace MvcApplication2.Controllers
{
    public class EmpController : Controller
    {
        //
        // GET: /Emp/
        UsersContext2 db = new UsersContext2();

        public ActionResult  Index()
        {

            List<Emp> EmpList = db.Emps.ToList();



           return View(EmpList);

        }
        public ActionResult IndexAngularJs()
        {

            return View();
        }
        public JsonResult GetAll()
        {


            List<Emp> Empes = db.Emps.ToList();
            List<EmpBase> Empes2 = new List<EmpBase>();
            foreach (Emp emp in Empes)
            {
                EmpBase emp2 = new EmpBase();
                emp2.EmpId = emp.EmpId;
                emp2.EmpName = emp.EmpName;
                emp2.Amount = emp.Amount;
                emp2.ImagePath = emp.ImagePath;
 
                Empes2.Add(emp2); 
            
            }
            return Json(Empes2, JsonRequestBehavior.AllowGet);
                
            
            
        }
        public JsonResult GetEmp(int id = 0)
        {
            Emp emp = db.Emps.Find(id);
            if (emp == null)
            {

                return null;
            }

            return Json(emp);

        }

        public ActionResult Create()
        {

            List<SelectListItem> list = new List<SelectListItem>() {
                new SelectListItem(){ Value="1", Text="ActionScript"},
                new SelectListItem(){ Value="2", Text="AppleScript"},
                new SelectListItem(){ Value="3", Text="Asp"},
                new SelectListItem(){ Value="4", Text="BASIC"},
                new SelectListItem(){ Value="5", Text="C"},
                new SelectListItem(){ Value="6", Text="C++"},
                new SelectListItem(){ Value="7", Text="Clojure"},
                new SelectListItem(){ Value="8", Text="COBOL"},
                new SelectListItem(){ Value="9", Text="ColdFusion"},
                new SelectListItem(){ Value="10", Text="Erlang"},
                new SelectListItem(){ Value="11", Text="Fortran"},
                new SelectListItem(){ Value="12", Text="Groovy"},
                new SelectListItem(){ Value="13", Text="Haskell"}, 
                new SelectListItem(){ Value="14", Text="instinctcoder.com"},
                new SelectListItem(){ Value="15", Text="Java"},
                new SelectListItem(){ Value="16", Text="JavaScript"},
                new SelectListItem(){ Value="17", Text="Lisp"},
                new SelectListItem(){ Value="18", Text="Perl"},
                new SelectListItem(){ Value="19", Text="PHP"},
                new SelectListItem(){ Value="20", Text="Python"},
                new SelectListItem(){ Value="21", Text="Ruby"},
                new SelectListItem(){ Value="22", Text="Scala"},
                new SelectListItem(){ Value="23", Text="Scheme"},
            };
            ViewBag.CityData = list;
 
            return View();
        }

          [HttpPost]
        public ActionResult Create(Emp emp, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    file.SaveAs(HttpContext.Server.MapPath("~/UpLoad/")
                                                          + file.FileName);
                    emp.ImagePath = file.FileName;
                }
                db.Emps.Add(emp);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }
        [HttpPost]
          public string AddUpdateEmp(Emp Emp)
          {
              String str = string.Empty;
              if (Emp != null)
              {
                  db.Emps.Add(Emp);
                  if(Emp.EmpId==0)
                  {
                      str="Add Record";

                  }
                  else
                  {
                      str = "Update Record";
                      db.Entry(Emp).State = EntityState.Modified;
                  }
                  
                      db.SaveChanges();
                      return str;
                  
              }
              else
              {
                  return "Invalid Employee";
              }
          }
        public ActionResult Edit(int id=0)
          {
              Emp emp = db.Emps.Find(id);

            if(emp==null)
            {

                return HttpNotFound();
            }


            List<SelectListItem> list = new List<SelectListItem>() {
                new SelectListItem(){ Value="1", Text="ActionScript"},
                new SelectListItem(){ Value="2", Text="AppleScript"},
                new SelectListItem(){ Value="3", Text="Asp"},
                new SelectListItem(){ Value="4", Text="BASIC"},
                new SelectListItem(){ Value="5", Text="C"},
                new SelectListItem(){ Value="6", Text="C++"},
                new SelectListItem(){ Value="7", Text="Clojure"},
                new SelectListItem(){ Value="8", Text="COBOL"},
                new SelectListItem(){ Value="9", Text="ColdFusion"},
                new SelectListItem(){ Value="10", Text="Erlang"},
                new SelectListItem(){ Value="11", Text="Fortran"},
                new SelectListItem(){ Value="12", Text="Groovy"},
                new SelectListItem(){ Value="13", Text="Haskell"}, 
                new SelectListItem(){ Value="14", Text="instinctcoder.com"},
                new SelectListItem(){ Value="15", Text="Java"},
                new SelectListItem(){ Value="16", Text="JavaScript"},
                new SelectListItem(){ Value="17", Text="Lisp"},
                new SelectListItem(){ Value="18", Text="Perl"},
                new SelectListItem(){ Value="19", Text="PHP"},
                new SelectListItem(){ Value="20", Text="Python"},
                new SelectListItem(){ Value="21", Text="Ruby"},
                new SelectListItem(){ Value="22", Text="Scala"},
                new SelectListItem(){ Value="23", Text="Scheme"},
            };
            ViewBag.CityData = list;
              return View(emp);

          }

        public ActionResult Details(int id=0)
        {
            Emp emp = db.Emps.Find(id);
            if(emp==null)
            {

                return HttpNotFound();
            }
            return View(emp);

        }

        public ActionResult Delete(int id=0)
        {
            Emp emp = db.Emps.Find(id);
            if(emp==null)
            {
                return HttpNotFound();

            }
            return View(emp);

        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id = 0)
        {
            Emp emp = db.Emps.Find(id);
            db.Emps.Remove(emp);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        [HttpPost]
        public ActionResult Edit(Emp emp)
        {
        try
        {
            
            //if (ModelState.IsValid)
            {
             //   var oldEmp = db.Emps.Find(emp.EmpId);
                //if (oldEmp != null)
                //{
                //    var attachedEntry = db.Entry(oldEmp);

                //    attachedEntry.CurrentValues.SetValues(emp);
                //}
                //else
                //{

                //    db.Emps.Add(emp);
                //}

              //  var PhonesSub = db.Phones.Where(p => p.EmpId == emp.EmpId);

                //foreach (Phone ss in PhonesSub)
                //{

                //    var test = emp.phones.Where(p => p.PhoneId == ss.PhoneId);
                //    if (test.Count() == 0)
                //    {
                //        db.Phones.Remove(ss);
                //    }
                //}

                //foreach (Phone newPhone in emp.phones)
                //{


                //    if (newPhone.PhoneId == 0)
                //    {
                //        db.Entry(newPhone).State = EntityState.Added;
                //        db.Phones.Add(newPhone);

                //    }
                //    else
                //    {
                //        var oldPhone = db.Phones.Find(newPhone.PhoneId );
                //        var attachedEntry = db.Entry(oldPhone);

                //        attachedEntry.CurrentValues.SetValues(newPhone);
                        


                //    }

                //}
                //emp.phones.Clear();  
               // db.Emps.Attach(emp); 
                //db.Entry(emp).State = EntityState.Modified;
               // db.Emps.Attach(emp);
//                System.Collections.Generic.ICollection <string> a=  new List<string>();
              //  a.Add("Phones");
               

            //  db.Entry(oldEmp).CurrentValues.SetValues(emp);
              //  db.Entry(oldEmp).Property("Phones").IsModified = true;
               // UsersContext2.SetProperties(emp, oldEmp,a);
              //  emp.phones.Clear(); 
                //db.DetailUpdate<Emp,Phone >(emp,"phones");
               db.Entry(emp).State = EntityState.Modified; 
                db.SaveChanges();
                 // If Sucess== 1 then Save/Update Successfull else there it has Exception
                return Json(new { Success = 1, EmpId = emp.EmpId, ex = "" });
                }
            //else
            //{
            //    return Json(new { Success = 0, ex ="Error" });
            //}
            }
            catch (Exception ex) 
            {
                // If Sucess== 0 then Unable to perform Save/Update Operation and send Exception to View as JSON
                return Json(new { Success = 0, ex = ex.Message.ToString() });
            }

        }
       

MvcApplication2/Views/Emp/Create.cshtml
@model MvcApplication2.Models.Emp

@{
    ViewBag.Title = "Create";
}

<script src="~/Scripts/jquery-1.8.2.min.js"></script>
<script src="~/Scripts/jquery-ui-1.8.24.min.js"></script>
<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />

<h2>Create</h2>





    <script type="text/javascript">
        $(document).ready(function () {

          

            $("#opener").on("click", function () {
                
                
                
                alert('2');
              
              //  $("#Test").dialog();
                alert('3');

            });
           
       
       
        

        });
    function openmdoel()
    {
      
 
    }
</script>
@using (Html.BeginForm("Create", "Emp", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Emp</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.EmpName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EmpName)
            @Html.ValidationMessageFor(model => model.EmpName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Amount)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Amount )
            @Html.ValidationMessageFor(model => model.Amount)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Phone)
            @Html.ValidationMessageFor(model => model.Phone)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Pass)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Pass)
            @Html.ValidationMessageFor(model => model.Pass)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.City)
        </div>
        <div class="editor-field">
            
            @Html.EditorFor(model => model.City)
            @Html.ValidationMessageFor(model => model.City)
        </div>
        <div class="editor-field">
            <input id="ImagePath" title="Upload a product image"
                   type="file" name="file" />
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    <input id="opener" type="button" value="open Model" onclick="openmdoel()" />
    @Html.ActionLink("Back to List", "Index")
</div>
<div id="Test" class="openDialog" style="display: none">
    <h1>  open model Form</h1>
</div>

MvcApplication2/Views/Emp/Delete.cshtml
@model MvcApplication2.Models.Emp

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Emp</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EmpName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EmpName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Amount )
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MvcApplication2/Views/Emp/Details.cshtml
@model MvcApplication2.Models.Emp

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Emp</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EmpName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EmpName)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Amount)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Amount)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Phone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Phone)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Pass)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Pass)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.City)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.City)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.ImagePath)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ImagePath)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.EmpId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcApplication2/Views/Emp/Edit.cshtml
@model MvcApplication2.Models.Emp

@{
    ViewBag.Title = "Edit";
}

<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
<script type="text/javascript">
    function AddPhone() {
        var table = document.getElementById("myTable")
        var PhoneName = document.getElementById("PhoneName");
        var PhoneNumber = document.getElementById("PhoneNumber");

        var row = table.insertRow(table.rows.length - 1);
        var cell1 = row.insertCell(0);
        var cell2 = row.insertCell(1);
        var cell3 = row.insertCell(2);
        var cell4 = row.insertCell(3);
        cell1.innerHTML = PhoneName.value;
        cell2.innerHTML = PhoneNumber.value;
        cell3.innerHTML = "0";
        cell4.innerHTML = " <input type=button value=Delete onclick=DeletePhone(this) />";
        PhoneName.value = "";
        PhoneNumber.value = "";

    }
    function DeletePhone(row) {


        var i = row.parentNode.parentNode.rowIndex;
        document.getElementById('myTable').deleteRow(i)


    }



    //This function is used for sending data(JSON Data) to SalesController
    function savedata() {
        // Step 1: Read View Data and Create JSON Object

        // Creating SalesSub Json Object
        var phones = { "PhoneId": "", "EmpId": "", "PhoneName": "", "PhoneNumber": "" };


        // Creating SalesMain Json Object
        var Empmain = { "EmpId": "", "EmpName": "", "Amount": "", "ImagePath": "", "Phone": "", "Email": "", "Pass": "", "City": "", "phones": [] };

        // Set Sales Main Value
        Empmain.EmpId = $("#EmpId").val();
        Empmain.EmpName = $("#EmpName").val();
        Empmain.Amount = $("#Amount").val();
        Empmain.ImagePath = $("#ImagePath").val();
        Empmain.Phone = $("#Phone").val();
        Empmain.Email = $("#Email").val();
        Empmain.Pass = $("#Pass").val();
        Empmain.City = $("#City").val();


        // Getting Table Data from where we will fetch Sales Sub Record
        // var oTable = $('.tbl').dataTable().fnGetData();

        var table = document.getElementById("myTable")
        debugger;;

        for (var i = 1; i < table.rows.length - 1; i++) {




            // Set SalesSub individual Value
            phones.PhoneId = table.rows[i].cells[2].innerHTML.trim();
            phones.EmpId = Empmain.EmpId;
            phones.PhoneName = table.rows[i].cells[0].innerHTML.trim();
            phones.PhoneNumber = table.rows[i].cells[1].innerHTML.trim();
            // adding to SalesMain.SalesSub List Item
            Empmain.phones.push(phones);
            phones = { "PhoneId": "", "EmpId": "", "PhoneName": "", "PhoneNumber": "" };


        }
        // Step 1: Ends Here

        debugger;;

        // Set 2: Ajax Post
        // Here i have used ajax post for saving/updating information
        $.ajax({
            url: '/Emp/Edit',
            data: JSON.stringify(Empmain),
            type: 'POST',
            contentType: 'application/json;',
            dataType: 'json',
            success: function (result) {


                if (result.Success == "1") {
                    window.location.href = "/Emp/index";
                }
                else {
                    alert(result.ex);
                }
            },
            error: function (result) {

                alert(result);
            }
        });


    }
</script>
<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Emp</legend>

        @Html.HiddenFor(model => model.EmpId)

        <div class="editor-label">
            @Html.LabelFor(model => model.EmpName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EmpName)
            @Html.ValidationMessageFor(model => model.EmpName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Amount)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Amount)
            @Html.ValidationMessageFor(model => model.Amount)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.ImagePath)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ImagePath)
            @Html.ValidationMessageFor(model => model.ImagePath)
        </div>
      
       
        <div class="editor-label">
            @Html.LabelFor(model => model.Phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Phone)
            @Html.ValidationMessageFor(model => model.Phone)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Pass)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Pass)
            @Html.ValidationMessageFor(model => model.Pass)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.City)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.City)
            @Html.ValidationMessageFor(model => model.City)
        </div>
        <div>
            <table id="myTable">
                <tr>
                    <th> Phone Name</th>
                    <th> Phone Numer</th>
                </tr>
                @foreach (var item in Model.phones)
                {
                   
                    
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.PhoneName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PhoneNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PhoneId)
                        </td>
                        <td>
                            <input type="button" value="Delete" onclick="DeletePhone(this)" />
                        </td>
                    </tr>
                }
                <tr>
                    <td>@Html.TextBox("PhoneName") </td>
                    <td>@Html.TextBox("PhoneNumber")</td>
                    <td><input type="button" value="Add Phone" onclick="AddPhone()" /></td>

                </tr>
            </table>
        </div>
        <div>
            
        </div>
        <p>
            <input type="button" value="Save" onclick="savedata()" />

        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication2/Views/Emp/Index.cshtml
@model IEnumerable<MvcApplication2.Models.Emp>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    
</p>
<p>
    @Html.ActionLink("Angular", "IndexAngularJs")
</p>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmpName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EmpName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Amount )
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImagePath )
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pass)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>


        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.EmpId }) |
            @Html.ActionLink("Details", "Details", new { id=item.EmpId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.EmpId })
        </td>
    </tr>
}

</table>

MvcApplication2/Views/Emp/IndexAngularJs.cshtml
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
<script src="~/Scripts/angular.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>

<div ng-app="myApp" ng-controller="myCntrl">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <h1> Employee Details Page</h1>

    <br />

    <input type="button" class="btnAdd" value=" Add Employee" ng-click="AddEmployeeDiv()" />

    <div class="divList">
        <div>
            Search Text <input type="text" ng-model="Search" />
        </div>
        <p class="divHead">Employee List</p>
        <table cellpadding="12" class="table table-bordered table-hover">
            <tr>
                <td><b>EmpId</b></td>
                <td><b>EmpName</b></td>
                <td><b>Amount</b></td>
                <td><b>ImagePath</b></td>
                <td><b>Actions</b></td>
            </tr>
            <tr ng-repeat="Emp in Empes  | filter: Search">
                <td>
                    {{Emp.EmpId}}
                </td>
                <td>
                    {{Emp.EmpName}}
                </td>
                <td>
                    {{Emp.Amount}}
                </td>
                <td>
                    {{Emp.ImagePath}}
                </td>
                <td>
                    <span ng-click="editEmployee(Emp)" class="btnAdd">Edit</span>
                    <span ng-click="deleteEmployee(Emp)" class="btnRed">Delete</span>
                </td>
            </tr>
        </table>
    </div>
    
        <div ng-show="divEmployee">



            <p class="divHead">{{Action}} Employee</p>
            <table>
                <tr>
                    <td><b>Id</b></td>
                    <td>
                        <input type="text" disabled="disabled" ng-model="EmpId" />
                    </td>
                </tr>
                <tr>
                    <td><b>Name</b></td>
                    <td>
                        <input type="text" ng-model="EmpName" />
                    </td>
                </tr>
                <tr>
                    <td><b>Amount</b></td>
                    <td>
                        <input type="text" ng-model="Amount" />
                    </td>
                </tr>
                <tr>
                    <td><b>ImagePath</b></td>
                    <td>
                        <input type="text" ng-model="ImagePath" />
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <input type="button" class="btnAdd" value="Save" ng-click="AddUpdateEmployee()" />
                    </td>
                </tr>
            </table>
        </div>
    
</div>


        <script src="~/Content/Angular/Module.js"></script>

<script src="~/Content/Angular/Controller.js"></script>
<script src="~/Content/Angular/Service.js"></script>

MvcApplication2/Views/Emp/_EditData.cshtml
@model MvcApplication2.Models.Emp

<fieldset>
    <legend>Emp</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EmpName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EmpName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Amount)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Amount)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ImagePath)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ImagePath)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.EmpId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcApplication2/Views/Emp/_PhoneDetails.cshtml
@model IEnumerable<MvcApplication2.Models.Phone>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmpId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EmpId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PhoneId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PhoneId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PhoneId })
        </td>
    </tr>
}

</table>