MvcApplication2/Controllers/ImageController.cs
using MvcApplication2.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcApplication2.Controllers
{
    public class ImageController : Controller
    {
        //
        // GET: /Image/
        UsersContext2 db = new UsersContext2();
        public ActionResult Index()
        {
            return View(db.Images.ToList());
        }


        public ActionResult Create()
        {

            return View();
        }

        public ActionResult Detail(int Id)
        {
            Image image = db.Images.Find(Id);
            if(image==null)
            {
                return HttpNotFound(); 

            }

            return View(image);
        }

        [HttpPost ]
        public ActionResult Create(Image img, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    file.SaveAs(HttpContext.Server.MapPath("~/Images/")
                                                          + file.FileName);
                    img.ImagePath = file.FileName;
                }
                db.Images.Add(img);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(img);
        }

    }
}

MvcApplication2/Views/Image/Create.cshtml
@model MvcApplication2.Models.Image

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Image", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Image</legend>
       
        <div class="editor-field">
            @Html.EditorFor(model => model.ImagePath)
            @Html.ValidationMessageFor(model => model.ImagePath)
        </div>
        <div class="editor-field">
            <input id="ImagePath" title="Upload a product image"
                   type="file" name="file" />
        </div>
        <p><input type="submit" value="Create" /></p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication2/Views/Image/Index.cshtml
@model IEnumerable<MvcApplication2.Models.Image>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ImagePath)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ImageId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ImageId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ImageId })
        </td>
    </tr>
}

</table>